[build]
#target = "aarch64-linux-android"
#target = "aarch64-apple-ios"

#target = "aarch64-linux-android"

#[target.aarch64-linux-android]
#ar = "/Users/klim/Projects/robius/shared-directory-utm/robius-open/NDK/arm64/bin/aarch64-linux-android-ar"
#linker = "/Users/klim/Projects/robius/shared-directory-utm/robius-open/NDK/arm64/bin/aarch64-linux-android-clang"